Finished cat, working on build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,22 @@
-#!/bin/sh
+#!/bin/bash
+declare -a programs=("cat" "echo" "head")
 if [ -z $1 ]; then
-	echo "hey"
+	for i in "${programs[@]}"; do
+		pushd "$i" > /dev/null
+		printf "\e[93;1mBuilding %s\n" "$i"
+		cargo build --release
+		if [ $? == 0 ]; then
+			if [ $i == "cat" ]; then
+				cp "target/release/main" ../build_dir/cat
+			else
+				cp "target/release/$i" ../build_dir
+			fi
+		else
+			popd > /dev/null
+			printf "\e[91mOne or more programs failed to build\n" > /dev/stderr
+			exit 1
+		fi
+		popd > /dev/null
+	done
 fi
 
